manifest_version = 2
name = "Graphics Settings"
version = "1.0.4"
game_version = "1.3.0"
author = "BiRabittoh"
description = "Overlay (F6) for the game's graphics settings."
code = "graphics_settings"
requires = "game_symbols >= 1.0.1"