manifest_version = 2
name = "Music Player"
version = "1.0.2"
game_version = "1.3.0"
author = "BiRabittoh"
description = "In-game music player and track browser. Press F8 to toggle."
code = "music_player"
